#ifndef CP_ABE_CLIENT_H
#define CP_ABE_CLIENT_H

#include "AccessPolicy.h"
#include "Global.h"
#include <memory>

#ifdef ESP32
#include <esp_random.h>
#endif

/**
 * @brief Class representing a client in the CP-ABE system
 */
class MaCpAbeClient {
  public:
    /**
     * @brief Nested class representing a share tree for attribute-based
     * encryption
     */
    class ShareTree {
      public:
        element_t lambda_share; ///< Lambda share for the tree node
        element_t omega_share;  ///< Omega share for the tree node
        element_t saved_result; ///< Saved intermediate result for computations
        bool has_result = false; ///< Flag indicating if the result is set
        std::vector<std::shared_ptr<ShareTree>>
            children; ///< Child nodes in the tree

        /**
         * @brief Initialize share element in Zr field
         * @param GP Global parameters for initialization
         */
        void initShareZr(GlobalParameter &GP);

        /**
         * @brief Initialize result element in GT field
         * @param GP Global parameters for initialization
         */
        void initResultGT(GlobalParameter &GP);

        /**
         * @brief Add a child node to the share tree
         * @param child Shared pointer to the child node
         */
        void addChild(std::shared_ptr<ShareTree> child);
    };

    std::string GID;                 ///< Global identifier for the client
    
    element_t key_material;          ///< Key material for encryption/decryption
    unsigned char *symmetric_key;    ///< Symmetric key for data encryption
    std::shared_ptr<ShareTree> root; ///< Root of the share tree
    auth_reference_t reference; ///< Reference from attribute to the authority
    GlobalParameter GP; ///< Global parameters for cryptographic operations

    /**
     * @brief Constructor for Client class
     * @param gid Global identifier for the client
     * @param GP Global parameters for cryptographic operations
     */
    MaCpAbeClient(const std::string &gid, GlobalParameter &GP);

    /**
     * @brief Generate a random number for key generation
     * @return Random unsigned integer
     */
    unsigned int generateRandomNumber();

    /**
     * @brief Generate key material from input
     * @param input Input element for key material generation
     * @param Return a random_number generated by calling generateRandomNumber
     */
    void generateKeyMaterial(element_t &input);

    /**
     * @brief Derive symmetric key from parameters
     * @param random_number Random number for key derivation
     * @param length Length of the symmetric key
     */
    void deriveSymmetricKey(const unsigned int random_number,
                            const size_t length);

    /**
     * @brief Build a share tree from an access policy node
     * @param node Access policy node
     * @param share_tree Share tree to build
     */
    static void buildTree(const std::shared_ptr<AccessPolicy::Node> &node,
                          const std::shared_ptr<ShareTree> &share_tree);

    static void deserializeGlobalParameter(GlobalParameter& gp, std::vector<uint8_t>& buffer);
};

#endif // CP_ABE_CLIENT_H
