import CodeBlock from '../components/CodeBlock'

export default function DataStructures() {
  return (
    <>
      <h1 className="page-title">Data Structures</h1>
      <p className="page-subtitle">
        Serializable objects that carry cryptographic material between library
        components and across the NDN network.
      </p>

      <p>
        All data structures in ABAC-NDN are designed to be serializable so
        they can be encoded as NDN data packet content and exchanged between
        nodes. The library exposes five core structures.
      </p>

      <h2>GlobalParameter</h2>
      <p>
        Holds the public global parameters of the cryptographic scheme.
        Generated once during system setup and shared with all participants
        via the NDN network.
      </p>
      <CodeBlock
        language="cpp"
        label="GlobalParameter"
        code={`struct GlobalParameter {
    Pairing   pairing;    // bilinear pairing group
    Generator generator;  // group generator g

    void serialize(std::ostream& out) const;
    static GlobalParameter deserialize(std::istream& in);
};`}
      />
      <p>
        The <code>Pairing</code> encodes the elliptic curve group and its
        parameters. The <code>Generator</code> is a fixed group element used
        as the base for all key derivations.
      </p>

      <h2>AccessPolicy</h2>
      <p>
        Represents an attribute-based access policy as a threshold tree. The
        tree is built from the policy string and embedded into every
        ciphertext.
      </p>
      <CodeBlock
        language="cpp"
        label="AccessPolicy"
        code={`class AccessPolicy {
public:
    void setPolicy(PolicyNode* root);

    void serializeAP(std::ostream& output,
                     const AccessPolicy& ap) const;
    static AccessPolicy deserializeAP(std::istream& input);

private:
    PolicyNode*              root;           // threshold tree root
    std::vector<std::string> leafAttributes; // attribute names at leaves
};`}
      />

      <h3>Policy Tree Nodes</h3>
      <p>
        The tree is composed of <em>threshold nodes</em> (k-of-n) and{' '}
        <em>leaf nodes</em> (single attributes):
      </p>
      <div className="table-wrapper">
        <table>
          <thead>
            <tr>
              <th>Node Type</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Threshold node</td>
              <td>
                Requires at least <em>k</em> of its <em>n</em> children to be
                satisfied. Represents AND (k=n), OR (k=1), or arbitrary
                threshold gates.
              </td>
            </tr>
            <tr>
              <td>Leaf node</td>
              <td>
                Names a single attribute (e.g., <code>DEPT_ENGINEERING</code>).
                Satisfied if the decryptor holds a private key for this
                attribute.
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2>PublicKey</h2>
      <p>
        Contains the public key material generated by an authority for a
        single attribute. Published to the NDN network and fetched by
        encryptors before encryption.
      </p>
      <CodeBlock
        language="cpp"
        label="PublicKey"
        code={`struct PublicKey {
    std::string authorityGid;
    std::string attribute;
    uint32_t    version;      // incremented on revocation

    // pairing group elements — opaque to application code
    // ...

    void serialize(std::ostream& out) const;
    static PublicKey deserialize(std::istream& in);
};`}
      />
      <p>
        The <code>version</code> field tracks revocation generations. After a
        revocation, the authority increments the version and publishes a new
        public key, invalidating old ciphertexts.
      </p>

      <h2>PrivateKey</h2>
      <p>
        Contains the private key material issued by an authority to a
        specific client (consumer) for a single attribute. Kept local to the
        consumer and never shared.
      </p>
      <CodeBlock
        language="cpp"
        label="PrivateKey"
        code={`struct PrivateKey {
    std::string clientGid;
    std::string attribute;
    std::string authorityGid;

    // pairing group elements — opaque to application code
    // ...

    void serialize(std::ostream& out) const;
    static PrivateKey deserialize(std::istream& in);
};`}
      />

      <h2>Update</h2>
      <p>
        An update token issued by an authority after revoking a client's
        access. Allows remaining valid clients to update their key material
        without contacting the authority again for a full key re-issue.
      </p>
      <CodeBlock
        language="cpp"
        label="Update"
        code={`struct Update {
    std::string clientGid;
    std::string attribute;
    uint32_t    fromVersion;
    uint32_t    toVersion;

    // update token group elements
    // ...

    void serialize(std::ostream& out) const;
    static Update deserialize(std::istream& in);
};`}
      />

      <div className="note-box">
        <strong>Serialization:</strong> All structures implement{' '}
        <code>serialize</code> / <code>deserialize</code> methods that encode
        them into a binary format suitable for NDN data packet payloads. The
        format is version-tagged for forward compatibility.
      </div>

      <h2>MaAbeClient (helper)</h2>
      <p>
        <code>MaAbeClient</code> is a higher-level helper that aggregates the
        client-side key material and derives the symmetric key used for
        actual data decryption:
      </p>
      <CodeBlock
        language="cpp"
        label="MaAbeClient"
        code={`class MaAbeClient {
public:
    void generateKeyMaterial(const std::string& seed);
    void deriveSymmetricKey(const std::string& nonce);

private:
    std::string GID;
    KeyMaterial keyMaterial;
    SymmetricKey symmetricKey;
};`}
      />
    </>
  )
}
